# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test + Linter Jobs

on:
  pull_request:
    branches: [ mainline ]

permissions:
  packages: read

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.23.6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
    - run: pnpm i --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.VIDDI_PAT }}
    - run: pnpm test
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.23.6
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.VIDDI_PAT }}
    - run: pnpm lint
