name: Target Multiple Node.js Versions and Operating Systems
on:
  pull_request:
    branches: [ mainline ]

permissions:
  packages: read

jobs:
  e2e:
    name: Running Tests.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [ 16.x ]
    steps:
      - uses: actions/checkout@v1
      # Setup node
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'
       
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VIDDI_PAT }}
      - run: npm run e2e:ci
      - uses: actions/upload-artifact@v2
        name: Save screenshots
        with:
          name: e2e-ss
          path: reports/
