# This is a basic workflow that is manually triggered

name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials from Staging account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::471993188491:role/Github-Action
          aws-region: us-west-1

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
      - name: Get into correct directory
        run: cd configuration
      - name: testing
        run: echo "hello"
      - run: cd configuration && npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VIDDI_PAT }}
      - run: pwd
      - run: cd configuration && npx cdk list
